### ISSUE TITLE
ATAC-seq handling question

### ISSUE THREAD

**Issue by hiranumn** [jpiper/pyDNase#19]
Would it be possible to provide explanations for why loffset and roffset of BamHandler for ATACseq data needs to be set to -5 and 4, respectively?

**Comment by jpiper** [comment]
Here's my explanation, I'll add it to the documentation as well :)

This is because the transposase inserts asymmetrically you have to shift the reads on each strand for them to line up and generate the signal.

From the original ATAC-seq paper - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3959825/

"For peak calling and footprinting, we adjusted the read start sites to represent the center of the transposon binding event. Previous descriptions of the Tn5 transposase show that the transposon binds as a dimer and inserts two adapters separated by 9 bps (main text ref. 11). Therefore, all reads aligning to the + strand were offset by +4 bps, and all reads aligning to the – strand were offset −5 bps."

**Comment by hiranumn** [comment]
Thank you for the answer!
